services:
  postgres:
    image: postgres:15
    container_name: scalar-ist-postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scalarist
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  scalardl-ledger-schema-loader:
    image: ghcr.io/scalar-labs/scalardl-schema-loader:3.12.2
    container_name: scalar-ist-ledger-schema-loader
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config/scalardb-for-schema.properties:/scalardb.properties
    environment:
      - SCALAR_DL_LICENSING_LICENSE_KEY=${SCALAR_DL_LEDGER_LICENSING_LICENSE_KEY}
      - SCALAR_DL_LICENSING_LICENSE_CHECK_CERT_PEM=${SCALAR_DL_LEDGER_LICENSING_LICENSE_CHECK_CERT_PEM}
    command:
      - "--config"
      - "/scalardb.properties"
      - "--coordinator"

  scalardl-ledger:
    image: ghcr.io/scalar-labs/scalardl-ledger:3.12.2
    container_name: scalar-ist-ledger
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "50051:50051"
      - "50052:50052"
      - "50053:50053"
    environment:
      - SCALAR_DB_CONTACT_POINTS=jdbc:postgresql://postgres:5432/scalarist
      - SCALAR_DB_USERNAME=postgres
      - SCALAR_DB_PASSWORD=postgres
      - SCALAR_DB_STORAGE=jdbc
      - SCALAR_DL_LEDGER_PROOF_ENABLED=false
      - SCALAR_DL_LEDGER_DIRECT_ASSET_ACCESS_ENABLED=true
      - SCALAR_DL_LICENSING_LICENSE_KEY=${SCALAR_DL_LEDGER_LICENSING_LICENSE_KEY}
      - SCALAR_DL_LICENSING_LICENSE_CHECK_CERT_PEM=${SCALAR_DL_LEDGER_LICENSING_LICENSE_CHECK_CERT_PEM}

  ist-schema-loader:
    image: ghcr.io/scalar-labs/scalardb-schema-loader:3.17.1
    container_name: scalar-ist-schema-loader
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config/scalardb-for-schema.properties:/scalardb.properties
      - ./schema/ist.transaction.json:/schema.json
    command:
      - "--config"
      - "/scalardb.properties"
      - "-f"
      - "/schema.json"

volumes:
  postgres-data:
