# ScalarDL Ledger configuration
scalar.db.contact_points=cassandra
scalar.db.contact_port=9042
scalar.db.storage=cassandra
scalar.db.username=cassandra
scalar.db.password=cassandra

# Ledger settings
scalar.dl.ledger.server.port=50051
scalar.dl.ledger.server.privileged_port=50053
scalar.dl.ledger.server.admin_port=50053
scalar.dl.ledger.proof.enabled=false
