scalar.db.contact_points=jdbc:postgresql://postgres:5432/scalarist
scalar.db.username=postgres
scalar.db.password=postgres
scalar.db.storage=jdbc

scalar.dl.ledger.server.port=50051
scalar.dl.ledger.server.privileged_port=50053
scalar.dl.ledger.server.admin_port=50053
scalar.dl.ledger.proof.enabled=false
